---
deployment:
  tasks:
    # API dizinini oluştur ve koru
    - /bin/mkdir -p /home/sin66vacom/public_html/api
    # Backend dosyalarını kopyala
    - /bin/cp -R backend/* /home/sin66vacom/public_html/api/
