---
deployment:
  tasks:
    # public_html'ı temizle (SSL ve backend dizinini koru)
    - /bin/find /home/sin66vacom/public_html -mindepth 1 -maxdepth 1 ! -name ".well-known" ! -name "backend" -exec /bin/rm -rf {} \;
    # Frontend dosyalarını kopyala
    - /bin/cp -R ./ /home/sin66vacom/public_html/
    # Backend dizinini oluştur
    - /bin/mkdir -p /home/sin66vacom/public_html/backend
    # Backend dosyalarını kopyala
    - /bin/cp -R backend/* /home/sin66vacom/public_html/backend/
    # Eski backend klasörünü dist'ten sil (artık public_html/backend'de)
    - /bin/rm -rf /home/sin66vacom/public_html/dist
