---
deployment:
  tasks:
    # public_html'ı temizle (SSL doğrulaması için .well-known'u ve api klasörünü koruyoruz)
    - /bin/find /home/sin66vacom/public_html -mindepth 1 -maxdepth 1 ! -name ".well-known" ! -name "api" -exec /bin/rm -rf {} \;
    # Frontend dosyalarını kopyala
    - /bin/cp -R public/* /home/sin66vacom/public_html/
    - /bin/cp index.html /home/sin66vacom/public_html/
    # Backend API klasörünü oluştur ve dosyaları kopyala
    - /bin/mkdir -p /home/sin66vacom/public_html/api
    - /bin/cp -R backend/* /home/sin66vacom/public_html/api/
