---
deployment:
  tasks:
    # public_html'ı temizle (SSL ve api dizinini koru)
    - /bin/find /home/sin66vacom/public_html -mindepth 1 -maxdepth 1 ! -name ".well-known" ! -name "api" -exec /bin/rm -rf {} \;
    # Frontend dosyalarını kopyala
    - /bin/cp -R ./ /home/sin66vacom/public_html/
    # API dizinini oluştur
    - /bin/mkdir -p /home/sin66vacom/public_html/api
    # Backend dosyalarını API dizinine kopyala
    - /bin/cp -R backend/* /home/sin66vacom/public_html/api/
    # Backend klasörünü public_html'den sil (gereksiz)
    - /bin/rm -rf /home/sin66vacom/public_html/backend
